### ISSUE TITLE
debug BubbleSort

### ISSUE THREAD

**Issue by Visweshvar-Axel** [Visweshvar-Axel/DSA-using-JAVA#4]
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9
	at com.ust.LP1.lesson2.Sorting.BubbleSort.sBubbleSort(BubbleSort.java:26)
	at com.ust.LP1.lesson2.Sorting.BubbleSort.main(BubbleSort.java:55)

                if(num[j]>num[j+1]){
                    swap(num, j,j+1);
                }} catch (ArrayIndexOutOfBoundsException e){
                    e.printStackTrace();
                    System.out.println("i"+i+"\nj"+j);
                }

**Comment by Visweshvar-Axel** [comment]
for(int j=0;j<num.length-i-1;j++){

-1 is the issue
